### ISSUE TITLE
How would server-side rendering work?

### ISSUE THREAD

**Issue by jrf0110** [tajo/react-titled#1]
I'm looking to use this on a couple of projects that do server rendering. Those projects do something like:

```javascript
const appStr = renderToString(<App />)
res.end(`
<!DOCTYPE html>
<html>
  <head>
    <title>${howDoesReactTitledPutTheTitleHere}</title>
  </head>
  <body>
    ${appStr}
  </body>
</html>
`)
```

Is there an existing mechanism for this?

**Comment by tajo** [comment]
I was thinking about it. It seems that the only way would be to implement `UNSAFE_componentWillMount` since that's afaik the only lifecycle method that's being called during SSR. `titled` now uses only componentDidMount, DidUpdate and WillIUnmount.

There is a lengthy discussion (including React team) about this [here](https://github.com/gaearon/react-side-effect/issues/40). It seems the solution is to use UCWM on the server until https://github.com/reactjs/rfcs/pull/8 lands.
